config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root "home#me"

  get "blog" => "posts#index"
  get "blog/*id" => "posts#show", as: :blog_post
  get "tags" => "tags#index"
  get "tags/:id" => "tags#show", as: :tag
  get "quotes" => "quotes#index"
  get "contributions" => "contributions#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contribution.rb
# frozen_string_literal: true
class Contribution
  def self.all
    I18n.t("contributions")
  end
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  before_create :generate_slug

  scope :with_tag, ->(tag) { where("tags @> ARRAY[?]", tag) }

  def self.all_tags
    pluck(:tags).flatten(1).uniq.sort_by(&:to_s).group_by { |tag| tag[0] }
  end

  def self.newest_first
    order(created_at: :desc)
  end

  def to_param
    slug
  end

  def to_s
    title
  end

  private

    def to_slug
      File.join created_at.strftime("%Y/%m/%d"), title.parameterize(separator: "_")
    end

    def generate_slug
      self.slug = to_slug
    end
end

app/models/quote.rb
# frozen_string_literal: true

class Quote
  attr_reader :text, :source

  def self.sample
    new $redis.hmget($redis.srandmember("quotes"), "text", "source")
  end

  def initialize(quote)
    @text = quote.first
    @source = quote.last
  end
end

app/models/render_markdown.rb
# frozen_string_literal: true

require "html/pipeline/juanito_fatas/nohtml_markdown_filter"
require "html/pipeline/juanito_fatas/emoji_filter"

class RenderMarkdown
  def initialize(content)
    @content = content
  end

  def call(**options)
    pipeline = HTML::Pipeline.new [
      HTML::Pipeline::JuanitoFatas::NohtmlMarkdownFilter,
      HTML::Pipeline::LinkifyGitHubFilter,
      HTML::Pipeline::SanitizationFilter,
      HTML::Pipeline::JuanitoFatas::EmojiFilter,
      HTML::Pipeline::RougeFilter,
    ], { gfm: true, **options }

    pipeline.call(content)[:output].to_s.html_safe
  end

  private

    attr_reader :content
end

app/models/repository.rb
class Repository
  attr_reader :url, :commits_url, :avatar_url, :title, :description

  def initialize(repo_info)
    @url = repo_info[:url]
    @commits_url = repo_info[:commits_url]
    @avatar_url = repo_info[:avatar_url]
    @title = repo_info[:title]
    @description = repo_info[:description]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def append_info_to_payload(payload)
    super
    payload[:request_id] = request.uuid
  end
end

app/controllers/contributions_controller.rb
class ContributionsController < ApplicationController
  def index
    @contributions = Contribution.all
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def me
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.newest_first
  end

  def show
    @post = Post.find_by!(slug: params[:id])
  end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  def index
    @quote = Quote.sample
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  class TagNotFound < ActiveRecord::RecordNotFound; end
  before_action :find_posts, only: :show

  def index
    @all_tags = Post.all_tags
  end

  def show
    if @posts.present?
      render "posts/index"
    else
      raise TagNotFound
    end
  end

  private

    def find_posts
      @posts = Post.with_tag(params[:id]).newest_first
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/emoji_helper.rb
module EmojiHelper
  def emojify(content)
    h(content).to_str.gsub(/:([\w+-]+):/) do |match|
      if emoji = Emoji.find_by_alias($1)
        %(<img class="emoji" alt="#$1" src="#{image_path("https://assets-cdn.github.com/images/icons/emoji/#{emoji.image_filename}")}">)
      else
        match
      end
    end.html_safe if content.present?
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def markdown_to_html(content)
    RenderMarkdown.new(content).call
  end
end

app/views/application/_google_analytics.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-80435360-1', 'auto');
  ga('send', 'pageview');
</script>

app/views/application/_meta.html.slim
.meta
  time.meta-date date=post.created_at itemprop="datePublished"
    = post.created_at.strftime("%b %d, %Y".freeze)
  ul.meta-tag-list
    - post.tags.each do |tag|
      li.meta-tag-item= link_to(tag, "/tags/#{tag}", "aria-label" => "Posts tagged with #{tag}", "itemprop" => "url")

app/views/application/_repository.slim
.repo-info
  .repo-logo
    = image_tag repository.avatar_url
    h4= repository.title
  p.truncate= emojify(repository.description)
  = link_to "View Project", repository.url, target: "_blank", rel: "noopener", class: "btn-repo", "aria-label" => "Link to this GitHub project", "itemprop" => "url"
  = link_to "My Commits", repository.commits_url, target: "_blank", rel: "noopener", class: "btn-repo", "aria-label" => "Link to my commits of this GitHub project", "itemprop" => "url"

app/views/application/_social-shared.html.erb
<a class="resp-sharing-button__link" href="https://twitter.com/intent/tweet/?text=<%= title %>&amp;url=<%= url %>&amp;via=JuanitoFatas" target="_blank" aria-label="">
  <div class="resp-sharing-button resp-sharing-button--twitter resp-sharing-button--small"><div aria-hidden="true" class="resp-sharing-button__icon resp-sharing-button__icon--solid">
    <svg version="1.1" x="0px" y="0px" width="24px" height="24px" viewBox="0 0 24 24" enable-background="new 0 0 24 24" xml:space="preserve">
        <g>
            <path d="M23.444,4.834c-0.814,0.363-1.5,0.375-2.228,0.016c0.938-0.562,0.981-0.957,1.32-2.019c-0.878,0.521-1.851,0.9-2.886,1.104 C18.823,3.053,17.642,2.5,16.335,2.5c-2.51,0-4.544,2.036-4.544,4.544c0,0.356,0.04,0.703,0.117,1.036 C8.132,7.891,4.783,6.082,2.542,3.332C2.151,4.003,1.927,4.784,1.927,5.617c0,1.577,0.803,2.967,2.021,3.782 C3.203,9.375,2.503,9.171,1.891,8.831C1.89,8.85,1.89,8.868,1.89,8.888c0,2.202,1.566,4.038,3.646,4.456 c-0.666,0.181-1.368,0.209-2.053,0.079c0.579,1.804,2.257,3.118,4.245,3.155C5.783,18.102,3.372,18.737,1,18.459 C3.012,19.748,5.399,20.5,7.966,20.5c8.358,0,12.928-6.924,12.928-12.929c0-0.198-0.003-0.393-0.012-0.588 C21.769,6.343,22.835,5.746,23.444,4.834z"/>
        </g>
    </svg>
    </div>
  </div>
</a>

<a class="resp-sharing-button__link" href="mailto:?subject=<%= title %>&amp;body=<%= url %>" target="_blank" aria-label="">
  <div class="resp-sharing-button resp-sharing-button--email resp-sharing-button--small"><div aria-hidden="true" class="resp-sharing-button__icon resp-sharing-button__icon--solid">
    <svg version="1.1" x="0px" y="0px" width="24px" height="24px" viewBox="0 0 24 24" enable-background="new 0 0 24 24" xml:space="preserve">
        <path d="M22,4H2C0.897,4,0,4.897,0,6v12c0,1.103,0.897,2,2,2h20c1.103,0,2-0.897,2-2V6C24,4.897,23.103,4,22,4z M7.248,14.434 l-3.5,2C3.67,16.479,3.584,16.5,3.5,16.5c-0.174,0-0.342-0.09-0.435-0.252c-0.137-0.239-0.054-0.545,0.186-0.682l3.5-2 c0.24-0.137,0.545-0.054,0.682,0.186C7.571,13.992,7.488,14.297,7.248,14.434z M12,14.5c-0.094,0-0.189-0.026-0.271-0.08l-8.5-5.5 C2.997,8.77,2.93,8.46,3.081,8.229c0.15-0.23,0.459-0.298,0.691-0.147L12,13.405l8.229-5.324c0.232-0.15,0.542-0.084,0.691,0.147 c0.15,0.232,0.083,0.542-0.148,0.691l-8.5,5.5C12.189,14.474,12.095,14.5,12,14.5z M20.934,16.248 C20.842,16.41,20.673,16.5,20.5,16.5c-0.084,0-0.169-0.021-0.248-0.065l-3.5-2c-0.24-0.137-0.323-0.442-0.186-0.682 s0.443-0.322,0.682-0.186l3.5,2C20.988,15.703,21.071,16.009,20.934,16.248z"/>
    </svg>
    </div>
  </div>
</a>

app/views/contributions/index.slim
section.contributions
  h2 My Open Source Contributions on GitHub
  p
    ' I contributed
    => link_to "some commits", "http://contributors.rubyonrails.org/contributors/juanito-fatas/commits/", target: "_blank", rel: "noopener", "aria-label" => "Link to my Rails commits", "itemprop" => "url"
    ' to
    = link_to "Rails", "https://github.com/rails/rails/", target: "_blank", rel: "noopener", "aria-label" => "Link to Rails GitHub project", "itemprop" => "url"
    ' .
    | The following is my adventures in the wonderland of Open Source 👇

  h3 id="hightlights" Highlights
  ul class="contribution-list"
    - @contributions[:highlights].each do |repo_info|
      li= render "repository", repository: Repository.new(repo_info)

  h3 id="projects" Projects
  ul class="contribution-list"
    - @contributions[:projects].each do |repo_info|
      li= render "repository", repository: Repository.new(repo_info)

  h3 id="libraries" Libraries
  ul class="contribution-list"
    - @contributions[:libraries].each do |repo_info|
      li= render "repository", repository: Repository.new(repo_info)

  h3 id="documentations" Documentations
  ul class="contribution-list"
    - @contributions[:documentations].each do |repo_info|
      li= render "repository", repository: Repository.new(repo_info)

  h3 id="translations" Translations
  p
    ' I maintain Chinese locale of
    = link_to "https://ruby-lang.org", "https://ruby-lang.org/", target: "_blank", rel: "noopener", "aria-label" => "Link to Ruby official website", "itemprop" => "url"
    ' . And
    ' I translated
    = link_to "Ruby on Rails Doctrine", "https://medium.com/@juanitofatas/ruby-on-rails-%E5%9F%BA%E6%9C%AC%E4%B8%BB%E7%BE%A9-f4cde39292a4#.c4zbum2k5", target: "_blank", rel: "noopener", "aria-label" => "Link to Ruby on Rails Doctrine translation on medium.com", "itemprop" => "url"
    ' ,
    = link_to "Ruby on Rails Guides", "http://rails.ruby.tw/", target: "_blank", rel: "noopener", "aria-label" => "Link to Ruby on Rails Guides (Traditional Chinese)", "itemprop" => "url"
    ' , and
    = link_to "Rails Girls Guides", "http://railsgirls.tw/", target: "_blank", rel: "noopener", "aria-label" => "Link to Rails Girls Guides (Traditional Chinese)", "itemprop" => "url"
    | . Some other work listed below:

  ul class="contribution-list"
    - @contributions[:translations].each do |repo_info|
      li= render "repository", repository: Repository.new(repo_info)

app/views/home/me.html.slim
header.short-introduction
  h2 Hi, I'm Juanito. I'm a software engineer.
  p
    ' I am interested in programming, web development, agile practices, software craftsmanship, and
    = link_to "humane development", "http://humanedevelopment.org", target: "_blank", rel: "noopener", "aria-label" => "http://humanedevelopment.org", "itemprop" => "url"
    ' . I write code, practice Test-Driven Development, Continuous Integration and other Agile practices at
    = link_to "Jolly Good Code", "http://www.jollygoodcode.com", target: "_blank", rel: "noopener", "aria-label" => "http://www.jollygoodcode.com", "itemprop" => "url"
    ' . I work as an apprentice and
    => link_to "contribute to Open Source", "/contributions", "aria-label" => "JuanitoFatas's Open Source Contributions Page", "itemprop" => "url"
    ' frequently, regular participants of community events, enjoy attending and
    => link_to "speaking at meetups and conferences", "https://speakerdeck.com/juanitofatas", target: "_blank", rel: "noopener", "aria-label" => "https://speakerdeck.com/juanitofatas", "itemprop" => "url"
    | .
  p
    ' I live in Taipei, Taiwan. In the past, I studied my bachelor degree in Leuven, Belgium.

  p
    ' The code of this site is available under
    = link_to "MIT License", "https://github.com/JuanitoFatas/JuanitoFatas", target: "_blank", rel: "noopener", "aria-label" => "Source page of this site", "itemprop" => "url"
    | .

  ul.link-list itemscope="" itemtype="https://www.schema.org/SiteNavigationElement"
    li itemprop="name"= link_to "Writing", "/blog", "aria-label" => "Blog", "itemprop" => "url"
    li itemprop="name"= link_to "Speaking", "https://speakerdeck.com/juanitofatas", target: "_blank", rel: "noopener", "aria-label" => "Speaking", "itemprop" => "url"
    li itemprop="name"= link_to "Twitter", "https://twitter.com/juanitofatas", target: "_blank", rel: "noopener", "aria-label" => "Twitter", "itemprop" => "url"
    li itemprop="name"= link_to "GitHub", "https://github.com/juanitofatas", target: "_blank", rel: "noopener", "aria-label" => "GitHub", "itemprop" => "url"
    li itemprop="name"= mail_to "me@juanitofatas.com", "Contact", "aria-label" => "Contact", "itemprop" => "url"
    li itemprop="name"= link_to "Quotes", quotes_path, "aria-label" => "Quotes", "itemprop" => "url"

app/views/layouts/application.html.slim
doctype 5
html lang="en"
  head
    title= title
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"

    = csrf_meta_tags

    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track": "reload"
    = javascript_include_tag "application", "data-turbolinks-track": "reload"
    = favicon_link_tag

  body itemscope="" itemtype="https://schema.org/WebPage"
    - if Rails.env.production?
      = render "google_analytics"

    .container
      h1#juanitofatas= link_to("Juanito Fatas", root_path, "aria-label" => "Back to Home Page", "itemprop" => "url")

      = yield

app/views/posts/index.html.slim
ul.topic-list
  li.topic-item= link_to("all", tags_path, "aria-label" => "All Tags", "itemprop" => "url")
  - %w(ruby rails).each do |tag|
    li.topic-item= link_to(tag, tag_path(tag), "aria-label" => "Posts tagged with #{tag}", "itemprop" => "url")

ul.tiny-post-list
  - @posts.each do |post|
    li.tiny-post
      h2.tiny-post-title= link_to(post.title, blog_post_path(post), "aria-label" => "A Blog post: #{post.title}", "itemprop" => "url")
      p.tiny-post-teaser= post.description
      = render "meta", post: post

app/views/posts/show.html.slim
article.post itemscope="" itemtype="https://schema.org/BlogPosting"
  header
    h1.title itemprop="name"= @post.title
    = render "meta", post: @post
  .post-body itemprop="articleBody"
    = markdown_to_html(@post.body)

hr

.social
  h4 Share this post
  = render "social-shared", title: @post.title, url: blog_post_url(@post)

app/views/quotes/index.slim
h2 My Favorite Quotes

blockquote.favorited-quote
 p
   | #{@quote.text}
   br
   | ― #{@quote.source}

app/views/tags/index.slim
ul.tag-list
  - @all_tags.each do |tag_title, tags|
    li.tag-item
      .tag-title= tag_title
      - tags.each do |tag|
        = link_to(tag, tag_path(tag), class: "tag", "aria-label" => "Posts tagged with #{tag}")